### ISSUE TITLE
Easier Setup

### ISSUE THREAD

**Issue by nickmitchko** [caretdev/django-iris#3]
Instead of requiring pip install <path to latest dbapi> as a separate manual step, we can install it as part of the requirements.txt automatically via url.

Requirements.txt can contain the latest absolute url to the dbapi driver, such as:

### Requirements.txt

```
https://github.com/intersystems-community/iris-driver-distribution/raw/main/intersystems_irispython-3.2.0-py3-none-any.whl
```

**Comment by daimor** [comment]
It would much easier if InterSystems would publish it as normal people do it.
