### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by vorg-san** [caretdev/django-iris#7]
Hi! 

I am trying to connect to this Server: **Cache Cache Objects Version 2018.1.4.505 Cache xDBC Server 8.01** which I am able to do with this Driver: **InterSystems Cache JDBC 2010.2.3.702**

However, when trying to connect with this django-iris package (same parameters as with jdbc driver), I only get: **TimeoutError: timed out**

Do you know if it is a version mismatch or if I can do anything else to debug and make it work?

**Comment by daimor** [comment]
Hi, I would not expect it to work with Caché, it is supposed to work only with IRIS.
But I'm sure timeout error, should not happen anyway.
I need some time to test it.

**Comment by vorg-san** [comment]
Wow that was a fast response! I did misconfigure, now I got the real error: **Exception: connection failed: IRIS xDBC protocol is not compatible**

**Comment by daimor** [comment]
So, yep, this error means, you really need IRIS
You may, try to use Community Edition, but start in nothreading mode there, with the common version, you will be able to use multithreading

**Comment by vorg-san** [comment]
can you point me in the direction of this Community Edition? Is it a cachè driver for python?

**Comment by grongierisc** [comment]
here is the community edition of IRIS : 

- intersystemsdc/iris-community:latest

if you have access to WRC, you can download it here : 

- https://wrc.intersystems.com/wrc/coDistEvaluation.csp

Is it a caché driver for python?

No :(

**Comment by vorg-san** [comment]
Thank you so much for the info! 
It will possibly serve as reference for future tries. Because of time constraints on the project, since Cachè is making it way too difficult, we will proceed with Oracle.

**Comment by daimor** [comment]
> since Cachè is making it way too difficult, we will proceed with Oracle.

That's very interesting, and I would like to discuss it. I'm an InterSystems employee but have not used anything but InterSystems in many projects where I participated. If you are ok to have a brief discussion over zoom, writer me dmitry@caretdev.com
